// =====================================================================
//  WhatsApp.gs
//
//  Add this as a NEW separate .gs file in your Apps Script project.
//  Do NOT touch your existing Code.gs.
//
//  HOW IT WORKS
//  ─────────────────────────────────────────────────────────────────
//  Your planned dates are generated by formulas, not manual typing.
//  onEdit / onChange triggers do NOT fire when a formula produces a
//  new value — so those approaches will never work for planned dates.
//
//  This script uses a TIME-BASED trigger instead:
//    • Runs automatically every hour (configurable)
//    • Scans every row for planned dates that are now populated
//    • Sends a WhatsApp to the responsible HOD with the form link
//    • Logs every sent message in a sheet called "WA_Log" to ensure
//      each task+flow combination is only notified ONCE (no duplicates)
//
//  QUICK SETUP (do this once)
//  ─────────────────────────────────────────────────────────────────
//  1. Paste this file into Apps Script as a new file (File → New → Script)
//  2. Verify the WA_CFG values below match your sheet structure
//  3. Run  setupWhatsAppTrigger()  once from the editor
//  4. Run  testWhatsAppSend()      to verify the API works
//  5. Done — the hourly trigger handles everything from here
// =====================================================================


// ─────────────────────────────────────────────────────────────────
//  CONFIGURATION  ← adjust if your sheet structure differs
// ─────────────────────────────────────────────────────────────────
var WA_CFG = {

  // Sheet names
  FMS_SHEET:  "FMS",      // Sheet that holds the flow tracking table
  HOD_SHEET:  "HOD",      // HOD directory  (col A = name, col B = phone)
  LOG_SHEET:  "WA_Log",   // Auto-created — tracks every sent message

  // Columns that carry task details (1-based, i.e. A=1, B=2 …)
  TASK_ID_COL:       15,  // Column O — unique task identifier
  ITEM_NAME_COL:     7,   // Column G — item / product name
  CUSTOMER_NAME_COL: 2,   // Column B — customer name

  // Flow block layout
  //   Flow 1 → cols Q–U  (Q=17),  HOD name in Q2
  //   Flow 2 → cols V–Z  (V=22),  HOD name in V2
  //   Flow 3 → cols AA–AE (AA=27), HOD name in AA2
  //   … and so on every 5 columns
  FLOW_START_COL: 17,   // Column Q — first column of Flow 1
  FLOW_SIZE:      5,    // Columns per flow block
  NUM_FLOWS:      8,    // Total number of flows
  HOD_NAME_ROW:   2,    // Row that contains each flow's HOD name
  DATA_START_ROW: 3,    // First row containing actual task data

  // Column offsets within each flow block (0-indexed from the block start)
  PLANNED_OFFSET:   0,  // [+0] Planned date  (PI)
  FORM_LINK_OFFSET: 3,  // [+3] Google Form link

  // WhatsApp API credentials
  API_URL:  "https://yourdigisathi.in/api/whatsapp-web/send-message",
  APP_KEY:  "c0a32d45-887c-48a7-8a35-1977773f0ebb",
  AUTH_KEY: "abcJnOSJ7zs71D110EXwaS9OkuuS9bEI11",

  // Trigger interval in hours (change to 0.5 for every 30 minutes, etc.)
  TRIGGER_HOURS: 1
};


// ─────────────────────────────────────────────────────────────────
//  SETUP — run this ONE TIME manually from the Apps Script editor
//  (Extensions → Apps Script → select setupWhatsAppTrigger → Run)
// ─────────────────────────────────────────────────────────────────
function setupWhatsAppTrigger() {
  // Remove any stale trigger for this function first
  var triggers = ScriptApp.getProjectTriggers();
  for (var i = 0; i < triggers.length; i++) {
    if (triggers[i].getHandlerFunction() === "checkAndSendWhatsApp") {
      ScriptApp.deleteTrigger(triggers[i]);
    }
  }

  // Install a fresh hourly (or configured interval) trigger
  ScriptApp.newTrigger("checkAndSendWhatsApp")
    .timeBased()
    .everyHours(WA_CFG.TRIGGER_HOURS)
    .create();

  // Make sure the log sheet exists
  ensureLogSheet_();

  Logger.log("✅ WhatsApp trigger installed. Runs every " + WA_CFG.TRIGGER_HOURS + " hour(s).");
  Logger.log("   Run testWhatsAppSend() next to verify API connectivity.");
}

// Removes the trigger (call this if you ever want to pause notifications)
function removeWhatsAppTrigger() {
  var triggers = ScriptApp.getProjectTriggers();
  var removed = 0;
  for (var i = 0; i < triggers.length; i++) {
    if (triggers[i].getHandlerFunction() === "checkAndSendWhatsApp") {
      ScriptApp.deleteTrigger(triggers[i]);
      removed++;
    }
  }
  Logger.log(removed > 0 ? "Trigger removed." : "No trigger found to remove.");
}


// ─────────────────────────────────────────────────────────────────
//  MAIN — called automatically by the time-based trigger
// ─────────────────────────────────────────────────────────────────
function checkAndSendWhatsApp() {

  var ss = SpreadsheetApp.getActiveSpreadsheet();

  // Load FMS sheet
  var fmsSheet = ss.getSheetByName(WA_CFG.FMS_SHEET);
  if (!fmsSheet) { Logger.log("ERROR: FMS sheet not found — check WA_CFG.FMS_SHEET"); return; }

  // Load HOD directory
  var hodSheet = ss.getSheetByName(WA_CFG.HOD_SHEET);
  if (!hodSheet) { Logger.log("ERROR: HOD sheet not found — check WA_CFG.HOD_SHEET"); return; }

  var lastRow = fmsSheet.getLastRow();
  if (lastRow < WA_CFG.DATA_START_ROW) { Logger.log("No data rows found."); return; }

  var lastCol = Math.max(
    fmsSheet.getLastColumn(),
    WA_CFG.FLOW_START_COL + WA_CFG.NUM_FLOWS * WA_CFG.FLOW_SIZE
  );

  // ── Batch-read the entire FMS sheet in one call (fast) ──────────
  var allData = fmsSheet.getRange(1, 1, lastRow, lastCol).getValues();

  // ── Build HOD name → phone lookup map ───────────────────────────
  var hodLastRow = hodSheet.getLastRow();
  var hodMap     = {};
  if (hodLastRow >= 2) {
    var hodData = hodSheet.getRange(2, 1, hodLastRow - 1, 2).getValues();
    for (var h = 0; h < hodData.length; h++) {
      var hodName  = hodData[h][0].toString().trim();
      var hodPhone = hodData[h][1].toString().trim();
      if (hodName && hodPhone) hodMap[hodName] = hodPhone;
    }
  }

  // ── Extract HOD name for each flow from HOD_NAME_ROW ─────────────
  var hodNameRowIdx = WA_CFG.HOD_NAME_ROW - 1; // 0-indexed
  var flowHODs = [];
  for (var fi = 0; fi < WA_CFG.NUM_FLOWS; fi++) {
    var colIdx = (WA_CFG.FLOW_START_COL - 1) + (fi * WA_CFG.FLOW_SIZE) + WA_CFG.PLANNED_OFFSET;
    flowHODs.push(
      colIdx < allData[hodNameRowIdx].length
        ? allData[hodNameRowIdx][colIdx].toString().trim()
        : ""
    );
  }

  // ── Load sent-log and build a fast lookup set ─────────────────────
  var logSheet  = ensureLogSheet_();
  var sentKeys  = buildSentKeySet_(logSheet);
  var newLogRows = [];

  // ── Scan every task row ───────────────────────────────────────────
  for (var row = WA_CFG.DATA_START_ROW; row <= lastRow; row++) {
    var ri     = row - 1; // 0-indexed row in allData
    var taskId = allData[ri][WA_CFG.TASK_ID_COL - 1];

    if (!taskId) continue; // Skip blank rows

    var itemName     = allData[ri][WA_CFG.ITEM_NAME_COL - 1];
    var customerName = allData[ri][WA_CFG.CUSTOMER_NAME_COL - 1];

    for (var fi = 0; fi < WA_CFG.NUM_FLOWS; fi++) {
      var plannedColIdx  = (WA_CFG.FLOW_START_COL - 1) + (fi * WA_CFG.FLOW_SIZE) + WA_CFG.PLANNED_OFFSET;
      var formLinkColIdx = (WA_CFG.FLOW_START_COL - 1) + (fi * WA_CFG.FLOW_SIZE) + WA_CFG.FORM_LINK_OFFSET;

      // Skip if planned date is missing
      var plannedVal = plannedColIdx < allData[ri].length ? allData[ri][plannedColIdx] : "";
      if (!plannedVal) continue;

      // Deduplication key: TaskID + Flow number
      var key = taskId.toString().trim() + "|F" + (fi + 1);
      if (sentKeys[key]) continue; // Already sent — skip

      // HOD for this flow
      var hodNameForFlow = flowHODs[fi];
      if (!hodNameForFlow) { Logger.log("Flow " + (fi+1) + ": no HOD name in row " + WA_CFG.HOD_NAME_ROW); continue; }

      var phone = hodMap[hodNameForFlow];
      if (!phone) { Logger.log("No phone for HOD: " + hodNameForFlow); continue; }

      var formLink = formLinkColIdx < allData[ri].length ? allData[ri][formLinkColIdx] : "";

      // Format date nicely
      var dateStr = (plannedVal instanceof Date)
        ? Utilities.formatDate(plannedVal, Session.getScriptTimeZone(), "dd/MM/yyyy HH:mm")
        : plannedVal.toString();

      // Send WhatsApp
      var ok = wa_send_(phone, hodNameForFlow, taskId, itemName, customerName, formLink, dateStr, fi + 1);

      if (ok) {
        sentKeys[key] = true; // Mark as sent in memory so we don't retry in same run
        newLogRows.push([taskId.toString(), fi + 1, hodNameForFlow, phone, dateStr, new Date()]);
        Logger.log("✅ Sent: " + key + " → " + hodNameForFlow + " (" + phone + ")");
      }
    }
  }

  // ── Append new rows to WA_Log ────────────────────────────────────
  if (newLogRows.length > 0) {
    logSheet
      .getRange(logSheet.getLastRow() + 1, 1, newLogRows.length, newLogRows[0].length)
      .setValues(newLogRows);
    Logger.log("Total WhatsApp messages sent this run: " + newLogRows.length);
  } else {
    Logger.log("No new WhatsApp messages to send this run.");
  }
}


// ─────────────────────────────────────────────────────────────────
//  WhatsApp API call  (returns true on success, false on failure)
// ─────────────────────────────────────────────────────────────────
function wa_send_(phone, hodName, taskId, itemName, customerName, formLink, plannedDate, flowNum) {

  var message =
    "Dear " + hodName + ",\n\n" +
    "A new task has been assigned to you in FMS (Flow " + flowNum + ").\n\n" +
    "Task ID      : " + taskId       + "\n" +
    "Item         : " + itemName     + "\n" +
    "Customer     : " + customerName + "\n" +
    "Planned Date : " + plannedDate  + "\n\n" +
    "Please fill the Google Form:\n" +
    (formLink ? formLink : "(Form link not yet assigned)") + "\n\n" +
    "Regards,\nFMS System";

  var options = {
    method:             "POST",
    contentType:        "application/x-www-form-urlencoded",
    muteHttpExceptions: true,
    payload: {
      app_key:  WA_CFG.APP_KEY,
      auth_key: WA_CFG.AUTH_KEY,
      to:       phone,
      type:     "text",
      message:  message
    }
  };

  try {
    var response = UrlFetchApp.fetch(WA_CFG.API_URL, options);
    var code     = response.getResponseCode();
    var body     = response.getContentText();

    Logger.log("WA API → " + phone + " | HTTP " + code + " | " + body);

    if (code === 200) {
      var json = JSON.parse(body);
      return json.status === "Success";
    }
    return false;

  } catch (err) {
    Logger.log("WA send error for " + phone + ": " + err.toString());
    return false;
  }
}


// ─────────────────────────────────────────────────────────────────
//  Log sheet helpers
// ─────────────────────────────────────────────────────────────────

// Returns the WA_Log sheet, creating it if it doesn't exist yet
function ensureLogSheet_() {
  var ss  = SpreadsheetApp.getActiveSpreadsheet();
  var log = ss.getSheetByName(WA_CFG.LOG_SHEET);
  if (!log) {
    log = ss.insertSheet(WA_CFG.LOG_SHEET);
    log.appendRow(["Task ID", "Flow #", "HOD Name", "Phone", "Planned Date", "Sent At"]);
    log.setFrozenRows(1);
    log.getRange("1:1").setFontWeight("bold");
    Logger.log("Created WA_Log sheet.");
  }
  return log;
}

// Reads WA_Log and returns a set of "TaskID|F#" keys already sent
function buildSentKeySet_(logSheet) {
  var keys = {};
  var lr   = logSheet.getLastRow();
  if (lr < 2) return keys;
  var data = logSheet.getRange(2, 1, lr - 1, 2).getValues(); // TaskID, Flow#
  for (var i = 0; i < data.length; i++) {
    var k = data[i][0].toString().trim() + "|F" + data[i][1].toString();
    keys[k] = true;
  }
  return keys;
}

// Clears the sent log — run manually if you want to re-send all notifications
// WARNING: this will cause WhatsApp messages to be sent again for all planned dates!
function clearWASentLog() {
  var ss  = SpreadsheetApp.getActiveSpreadsheet();
  var log = ss.getSheetByName(WA_CFG.LOG_SHEET);
  if (!log) { Logger.log("WA_Log sheet not found."); return; }
  var lr = log.getLastRow();
  if (lr > 1) {
    log.deleteRows(2, lr - 1);
    Logger.log("WA_Log cleared. Next trigger run will re-send all notifications.");
  } else {
    Logger.log("WA_Log is already empty.");
  }
}


// ─────────────────────────────────────────────────────────────────
//  TEST — run manually to verify API connectivity before going live
//  Replace the phone number with a real number you can check
// ─────────────────────────────────────────────────────────────────
function testWhatsAppSend() {
  var result = wa_send_(
    "91XXXXXXXXXX",        // ← Replace with a real phone in international format (no +)
    "Test HOD",
    "TASK-TEST-001",
    "Sample Item Name",
    "Sample Customer",
    "https://forms.gle/yourformlink",
    "28/05/2026 10:00",
    1
  );
  Logger.log(result
    ? "✅ Test message sent successfully!"
    : "❌ Test failed — check the log above for API error details"
  );
}
